/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/InfinityTower.gltf -ts 
*/

import * as THREE from "three";
import React from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Cylinder: THREE.Mesh;
    Cylinder_1: THREE.Mesh;
    Cylinder_2: THREE.Mesh;
  };
  materials: {
    Floor: THREE.MeshStandardMaterial;
    Glass: THREE.MeshPhysicalMaterial;
    Metal: THREE.MeshStandardMaterial;
  };
  animations: THREE.AnimationAction[];
};

export type FloorProps = {
  color: string;
  windowsTint: string;
};

export function Floor(props: React.ComponentProps<"group"> & FloorProps) {
  const { nodes, materials } = useGLTF(
    "/InfinityTower.gltf"
  ) as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder.geometry}
        material={materials.Floor}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder_1.geometry}
        material={materials.Glass}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder_2.geometry}
        material={materials.Metal}
      />
    </group>
  );
}

useGLTF.preload("/InfinityTower.gltf");
