/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/InfinityTower.gltf -ts 
*/

import * as THREE from "three";
import React from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Cylinder: THREE.Mesh;
    Cylinder_1: THREE.Mesh;
    Cylinder_2: THREE.Mesh;
  };
  materials: {
    Floor: THREE.MeshStandardMaterial;
    Glass: THREE.MeshPhysicalMaterial;
    Metal: THREE.MeshStandardMaterial;
  };
  animations: THREE.AnimationAction[];
};

export type FloorProps = {
  color: string;
  windowsTint: string;
};

export function Floor(props: React.ComponentProps<"group"> & FloorProps) {
  const { nodes, materials } = useGLTF(
    "/InfinityTower.gltf"
  ) as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Cylinder.geometry}>
        <meshStandardMaterial
          color={props.color}
          side={THREE.DoubleSide}
          roughness={0.6}
          metalness={0.3}
        />
      </mesh>
      <mesh castShadow receiveShadow geometry={nodes.Cylinder_1.geometry}>
        <meshPhongMaterial
          color={props.windowsTint}
          transparent
          opacity={0.7}
          side={THREE.DoubleSide}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder_2.geometry}
        material={materials.Metal}
      >
        <meshStandardMaterial
          color={"#888888"}
          roughness={0.4}
          metalness={0.8}
        />
      </mesh>
    </group>
  );
}

useGLTF.preload("/InfinityTower.gltf");
